apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashu-lb001
  name: ashu-lb001
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector: # pod finder dynamically 
    app: ashu-app-ui # here we put label of deployment template at selector 
  type: LoadBalancer
status:
  loadBalancer: {}
